version: "3"
services:
    app:
        image: "Orbitalis/indexsite"
        build:
            context: .
        restart: always
        networks:
            traefik_net:
            mongoCluster:
        labels:
            - traefik.enable=true
            - traefik.http.routers.Orbitalis.entrypoints=https
            - traefik.http.routers.Orbitalis.rule=Host(`Orbitalis.store`)
            - traefik.http.routers.Orbitalis.tls=true
            - traefik.http.routers.Orbitalis.tls.certresolver=letsEncrypt
            - traefik.http.services.Orbitalis.loadbalancer.server.port=3000

networks:
    traefik_net:
        external: true
    mongoCluster:
        external: true
